cuda: True
debug: False
save_dir: save
name: Bart
train_dataset: ET_1_1_train.txt # ET_train.txt or ET_1_1_train.txt or ET_1_n_train.txt
pretrained_model: facebook/bart-base # facebook/bart-base
append_another_bos: False
append_sep_token: False # True or False
is_in_edge: True
is_out_edge: True
max_epoch: 100 # default: 100
train_batch_size: 8
valid_batch_size: 8
test_batch_size: 8
num_workers: 4 # debug 0
temperature: 0.5
repetition_penalty: 1.5
n_gpus: 1
max_input_length: 256
max_output_length: 256
gradient_accumulation_steps: 1
max_grad_norm: 1.0
early_stopping: True
optimizer:
  algorithm: Adam
  learning_rate: 1.0e-04
valid:
  valid_dataset: ET_1_1_valid.txt # ET_valid.txt or ET_1_1_valid.txt or ET_1_n_valid.txt or ET_unobserved_vaild.txt
  valid_epoch: 1
  num_beams: 5
  length_penalty: 1.0
  max_output_length: 256
  clean_up_spaces: True
  save_outputs: True
  save_one_batch: True
test:
  test_dataset: ET_1_1_test.txt # ET_test.txt or ET_1_1_test.txt or ET_1_n_test.txt or ET_unobserved_test.txt
  unobserved_test_dataset: ET_1_1_unobserved_test.txt # ET_unobserved_test.txt or ET_1_1_unobserved_test.txt or ET_1_n_unobserved_test.txt
  save_outputs: True
  max_output_length: 128
  get_from_file: False
  get_from_model: True
  file_path: save/FB15kET/ET_test