cuda: False
debug: True
save_dir: save
name: JointGT
tokenizer_path: pretrain_model/jointgt_bart # pretrain_model/jointgt_bart or  pretrain_model/jointgt_t5
model_path: pretrain_model/jointgt_bart # pretrain_model/jointgt_bart or  pretrain_model/jointgt_t5
pretrained_model: Bart # Bart or T5
append_another_bos: False
is_in_edge: True
is_out_edge: True
max_node_length: 50
max_edge_length: 60
max_epoch: 1 # default: 100
train_batch_size: 1
valid_batch_size: 1
test_batch_size: 1
num_workers: 0 # debug
temperature: 0.5
n_gpus: 0
max_input_length: 256
max_output_length: 128
gradient_accumulation_steps: 1
max_grad_norm: 1.0
early_stopping: False
optimizer:
  algorithm: Adam
  learning_rate: 0.001
valid:
  valid_epoch: 10
  num_beams: 5
  length_penalty: 1.0
  max_output_length: 128
  clean_up_spaces: True
  save_outputs: False
test:
  test_dataset: ET_1_1_test.txt # ET_test.txt or ET_1_1_test.txt or ET_1_n_test.txt or ET_unobserved_test.txt
  save_outputs: True