defaults:
  - data/YAGO43kET # data/FB15kET or data/YAGO43kET
  - model/JointGT # model/JointGT or model/T5 or model/Bart
preprocess:
  load_ET: False
  load_KG: True
  neighbor_sampling: True
  neighbor_num: 10
  num_layers: 1

